server:
  port: 8080

spring:
  application:
    name: proxy-toolkit

  datasource:
    url: jdbc:postgresql://localhost:5446/app
    username: app
    password: app

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true

  cache:
    type: caffeine

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      enabled: true
# matches @ConfigurationProperties(prefix="proxy-toolkit")
proxy-toolkit:
  enabled: true
  max-payload-chars: 20000
  exclude-packages:
    - org.springframework
    - jakarta
    - java
    - com.zaxxer

security:
  api-key:
    pepper: ${API_KEY_PEPPER:}
    hash-algorithm: SHA-256

logging:
  level:
    root: INFO
    com.github.dimitryivaniuta: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO

    # only enable when debugging DB issues
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n%wEx"
